Lection1
js-tasks-ru/htmlcss-20220616_risorsedaffari pull request #3
Opened 2022-06-22 23:04 UTC by AntonSteshenko

Только кнопки, аккордеон не успею, останусь должен

2022-06-22 23:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-23 14:26 UTC, GSemikozov requested changes

2022-06-23 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину лучше жестко не фиксировать (длинный текст - и верста сломалась :))

2022-06-23 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
не хватает font-family

2022-06-23 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  font-size: 16px;
и паддингов

2022-06-23 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  color: rgba(255, 255, 255, 0.5);
тут прозрачность дублируется)

2022-06-23 14:26 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
лучше pointer-events: none

2024-12-20 07:39 UTC, closed without merging